# Generated by Django 3.1.1 on 2021-03-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20210317_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order',
            new_name='orderlist',
        ),
    ]
