# Generated by Django 3.1.1 on 2021-03-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20210317_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='user',
        ),
    ]
