# Generated by Django 3.1.1 on 2021-03-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_orderinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='messages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
