# Generated by Django 3.1.1 on 2021-03-17 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20210317_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='messages',
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.BooleanField(default=False)),
                ('messages', models.TextField()),
                ('orderinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='item.orderinfo')),
            ],
        ),
    ]
