# Generated by Django 3.1.1 on 2021-03-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20210317_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='messages',
        ),
        migrations.AddField(
            model_name='status',
            name='messages',
            field=models.ManyToManyField(to='item.Updates'),
        ),
    ]
